name: my-check

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: make test
